import { NextRequest, NextResponse } from "next/server";
import type { SOPResult } from "@/types/sop";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function generateRevealHtml(data: SOPResult): string {
  const slides: string[] = [];

  // Title slide
  slides.push(`
    <section data-background-gradient="linear-gradient(135deg, #1e1b4b 0%, #0f172a 50%, #1e1b4b 100%)">
      <h1 style="font-size:2.2em;">SOP Training Modules</h1>
      <p style="opacity:0.7;margin-top:1em;">
        <span style="background:rgba(99,102,241,0.2);padding:4px 12px;border-radius:4px;margin:0 4px;">${escapeHtml(data.analysis.sop_type)}</span>
        <span style="background:rgba(99,102,241,0.2);padding:4px 12px;border-radius:4px;margin:0 4px;">${escapeHtml(data.analysis.audience)}</span>
        <span style="background:rgba(99,102,241,0.2);padding:4px 12px;border-radius:4px;margin:0 4px;">${escapeHtml(data.analysis.complexity)}</span>
      </p>
      <p style="opacity:0.4;font-size:0.5em;margin-top:2em;">Generated by SOP Trainer</p>
    </section>
  `);

  // Overview slide
  slides.push(`
    <section>
      <h2>Overview</h2>
      <p style="text-align:left;font-size:0.75em;line-height:1.8;max-width:800px;margin:0 auto;">${escapeHtml(data.overview)}</p>
    </section>
  `);

  // Training module slides — 2 slides per module to avoid overflow
  data.training_modules.forEach((mod, i) => {
    // Slide A: objective + what to do + why it matters
    slides.push(`
      <section>
        <p style="font-size:0.45em;opacity:0.5;letter-spacing:0.1em;text-transform:uppercase;">Module ${i + 1} of ${data.training_modules.length}</p>
        <h2 style="color:#a78bfa;font-size:1.1em;margin:0.3em 0 0.8em;">${escapeHtml(mod.learning_objective)}</h2>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:28px;text-align:left;font-size:0.6em;">
          <div style="background:rgba(129,140,248,0.05);padding:16px;border-radius:8px;border-top:2px solid #818cf8;">
            <p style="color:#818cf8;font-weight:600;margin-bottom:8px;">What to Do</p>
            <p style="opacity:0.9;line-height:1.7;">${escapeHtml(mod.what_to_do)}</p>
          </div>
          <div style="background:rgba(129,140,248,0.05);padding:16px;border-radius:8px;border-top:2px solid #6366f1;">
            <p style="color:#818cf8;font-weight:600;margin-bottom:8px;">Why It Matters</p>
            <p style="opacity:0.9;line-height:1.7;">${escapeHtml(mod.why_it_matters)}</p>
          </div>
        </div>
        ${mod.prerequisite ? `<p style="font-size:0.5em;opacity:0.5;margin-top:16px;text-align:left;"><em>Prerequisite: ${escapeHtml(mod.prerequisite)}</em></p>` : ""}
      </section>
    `);

    // Slide B: example + common mistake
    slides.push(`
      <section>
        <p style="font-size:0.45em;opacity:0.5;letter-spacing:0.1em;text-transform:uppercase;">Module ${i + 1} — Practice & Pitfalls</p>
        <h2 style="color:#a78bfa;font-size:1.1em;margin:0.3em 0 0.8em;">${escapeHtml(mod.learning_objective)}</h2>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:28px;text-align:left;font-size:0.6em;">
          <div style="background:rgba(52,211,153,0.05);padding:16px;border-radius:8px;border-top:2px solid #34d399;">
            <p style="color:#34d399;font-weight:600;margin-bottom:8px;">Real-World Example</p>
            <p style="opacity:0.9;line-height:1.7;">${escapeHtml(mod.example)}</p>
          </div>
          <div style="background:rgba(251,191,36,0.05);padding:16px;border-radius:8px;border-top:2px solid #fbbf24;">
            <p style="color:#fbbf24;font-weight:600;margin-bottom:8px;">Common Mistake</p>
            <p style="opacity:0.9;line-height:1.7;">${escapeHtml(mod.common_mistake)}</p>
          </div>
        </div>
      </section>
    `);
  });

  // Decision scenarios slide
  if (data.decision_scenarios && data.decision_scenarios.length > 0) {
    const scenarioItems = data.decision_scenarios.map((ds, i) => `
      <div style="text-align:left;margin-bottom:20px;background:rgba(255,255,255,0.03);padding:16px;border-radius:8px;">
        <p style="font-size:0.7em;"><strong style="color:#c084fc;">Scenario ${i + 1}:</strong> ${escapeHtml(ds.situation)}</p>
        <p style="font-size:0.6em;margin-top:6px;"><strong>Decision:</strong> ${escapeHtml(ds.decision)}</p>
        <p style="font-size:0.55em;opacity:0.7;margin-top:4px;"><em>Reasoning: ${escapeHtml(ds.reasoning)}</em></p>
      </div>
    `).join("");

    slides.push(`
      <section>
        <h2>Decision Scenarios</h2>
        ${scenarioItems}
      </section>
    `);
  }

  // Quiz slides — 2 slides per question (question+options, then answer+explanation)
  if (data.quiz && data.quiz.length > 0) {
    slides.push(`
      <section>
        <h2>Assessment Quiz</h2>
        <p style="opacity:0.6;font-size:0.7em;">${data.quiz.length} questions &mdash; navigate with arrow keys</p>
        <p style="opacity:0.4;font-size:0.55em;margin-top:8px;">Each question is followed by the answer on the next slide</p>
      </section>
    `);

    data.quiz.forEach((q, i) => {
      const optionsHtml = q.options.map((opt, oi) => {
        const letter = String.fromCharCode(65 + oi);
        return `
          <div style="display:flex;align-items:flex-start;gap:10px;padding:10px 14px;margin:6px 0;background:rgba(255,255,255,0.04);border-radius:6px;border:1px solid rgba(255,255,255,0.06);">
            <span style="font-weight:700;color:#6366f1;min-width:20px;">${letter}.</span>
            <span style="opacity:0.9;">${escapeHtml(opt)}</span>
          </div>`;
      }).join("");

      // Slide 1: question + options
      slides.push(`
        <section>
          <div style="display:flex;align-items:center;gap:10px;margin-bottom:16px;">
            <span style="font-size:0.45em;background:rgba(99,102,241,0.2);color:#818cf8;padding:3px 10px;border-radius:4px;text-transform:uppercase;letter-spacing:0.08em;">${escapeHtml(q.type)}</span>
            <span style="font-size:0.45em;opacity:0.4;">Question ${i + 1} of ${data.quiz.length}</span>
          </div>
          <h3 style="font-size:0.85em;line-height:1.4;margin-bottom:20px;">${escapeHtml(q.question)}</h3>
          <div style="text-align:left;max-width:720px;margin:0 auto;font-size:0.6em;">
            ${optionsHtml}
          </div>
          <p style="font-size:0.4em;opacity:0.3;margin-top:20px;">→ Next slide reveals the answer</p>
        </section>
      `);

      // Slide 2: answer + explanation
      slides.push(`
        <section>
          <div style="display:flex;align-items:center;gap:10px;margin-bottom:16px;">
            <span style="font-size:0.45em;background:rgba(99,102,241,0.2);color:#818cf8;padding:3px 10px;border-radius:4px;text-transform:uppercase;letter-spacing:0.08em;">${escapeHtml(q.type)}</span>
            <span style="font-size:0.45em;opacity:0.4;">Question ${i + 1} of ${data.quiz.length} — Answer</span>
          </div>
          <h3 style="font-size:0.75em;line-height:1.4;opacity:0.7;margin-bottom:20px;">${escapeHtml(q.question)}</h3>
          <div style="text-align:left;max-width:720px;margin:0 auto;">
            <div style="background:rgba(52,211,153,0.1);border:1px solid rgba(52,211,153,0.3);border-left:4px solid #34d399;padding:16px 20px;border-radius:8px;margin-bottom:16px;">
              <p style="font-size:0.55em;color:#34d399;font-weight:700;margin-bottom:4px;text-transform:uppercase;letter-spacing:0.06em;">Correct Answer</p>
              <p style="font-size:0.7em;font-weight:600;">${escapeHtml(q.answer)}</p>
            </div>
            <div style="background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.07);padding:16px 20px;border-radius:8px;">
              <p style="font-size:0.5em;opacity:0.5;font-weight:600;margin-bottom:6px;text-transform:uppercase;letter-spacing:0.06em;">Explanation</p>
              <p style="font-size:0.65em;opacity:0.9;line-height:1.7;">${escapeHtml(q.explanation)}</p>
            </div>
          </div>
        </section>
      `);
    });
  }

  // End slide
  slides.push(`
    <section data-background-gradient="linear-gradient(135deg, #1e1b4b 0%, #0f172a 50%, #1e1b4b 100%)">
      <h2>Training Complete</h2>
      <p style="opacity:0.6;">Thank you for completing this SOP training module.</p>
    </section>
  `);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SOP Training — ${escapeHtml(data.analysis.sop_type)}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/reveal.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/theme/night.css">
  <style>
    .reveal { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    .reveal h1, .reveal h2, .reveal h3 { font-weight: 600; }
    .reveal h2 { font-size: 1.4em; margin-bottom: 0.5em; }
    .reveal h3 { font-size: 1.1em; }
    .reveal p { line-height: 1.6; margin: 0; }
    .reveal .slides section {
      height: 100%;
      box-sizing: border-box;
      padding: 30px 40px !important;
      display: flex !important;
      flex-direction: column;
      justify-content: center;
    }
    .reveal .slides { text-align: center; }
  </style>
</head>
<body>
  <div class="reveal">
    <div class="slides">
      ${slides.join("\n")}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/reveal.js"><\/script>
  <script>
    Reveal.initialize({
      hash: true,
      transition: 'slide',
      slideNumber: true,
      controls: true,
      progress: true,
      center: true,
      disableLayout: false,
      width: 1280,
      height: 720,
      margin: 0.04,
    });
  <\/script>
</body>
</html>`;
}

export async function POST(request: NextRequest) {
  try {
    const data: SOPResult = await request.json();

    if (!data.overview || !data.training_modules) {
      return NextResponse.json(
        { error: "Invalid SOP data provided." },
        { status: 400 }
      );
    }

    const html = generateRevealHtml(data);

    return new NextResponse(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": "attachment; filename=sop-training-slides.html",
      },
    });
  } catch {
    return NextResponse.json(
      { error: "Failed to generate slides." },
      { status: 500 }
    );
  }
}
